name: chat_app
description: A messaging app created using Flutter and Google Firebase


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: KoHo
      fonts:
        - asset: fonts/KoHo-Bold.ttf
          weight: 800
        - asset: fonts/KoHo-BoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/KoHo-SemiBold.ttf
          weight: 700
        - asset: fonts/KoHo-Medium.ttf
          weight: 600
        - asset: fonts/KoHo-MediumItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/KoHo-Regular.ttf
          weight: 500
        - asset: fonts/KoHo-Light.ttf
          weight: 400
        - asset: fonts/KoHo-ExtraLight.ttf
          weight: 300
    - family: Londrina Shadow
      fonts:
        - asset: fonts/LondrinaShadow-Regular.ttf